### ISSUE TITLE
Feature Request: "one of" constraints

### ISSUE THREAD

**Issue by Yagich** [rametta/zodot#3]
Hey, thanks so much for the plugin!

I'm working on a Godot app that can take requests over WebSocket, and I'd like to restrict certain dictionary/object keys to be of any one element of a set, something like:

```gdscript
var Schema := Z.schema({
	"name": Z.string().one_of(["foo", "bar"])
})
```

I haven't read through the code too thoroughly yet, but I can make a PR if this is desired.

**Comment by rametta** [comment]
This is already available as z.union or z.enum. Let me know if that's what you're looking for

**Comment by Yagich** [comment]
As I understand, `z.union` works only for type constraints and not values, and `z.zenum` works for godot enums, which are stored as dictionaries internally. What I was meaning was more that it would match a list of value literals:

```gdscript
var Schema := Z.schema({
	"name": Z.string().one_of(["foo", "bar"])
})

Schema.parse({"name": "foo"}).ok() #true
Schema.parse({"name": "bar"}).ok() #true
Schema.parse({"name": "baz"}).ok() #false
```

**Comment by Yagich** [comment]
Another approach that's more in line with Zod would be to add a new `literal` validator that can then be used within a `z.union`. Mockup code:

```gdscript
class_name z_literal extends Zodot

var _value: Variant

func _init(value: Variant):
	_value = value

func _valid_type(value: Variant) -> bool:
	return true

func parse(value: Variant, field: String = "") -> ZodotResult:
	if _coerce and typeof(value) == TYPE_STRING:
		value = str_to_var(value)
	
	if _nullable and value == null:
		return ZodotResult.good(value)
	
	if value == _value:
		return ZodotResult.good(value)
	
	return ZodotResult.constraint_error(field, "Value is not equal to literal")

```

**Comment by rametta** [comment]
Yes I was thinking a z.literal would be great. If you can please open a PR to add that, otherwise I will do it in the coming weeks

**Comment by Yagich** [comment]
Will do!
